madhuri:
what to do with GetOfferConfigSummary.segments_data_filter?
	this also needs to be converted in to query

i think if data.getlist("segment_id", None) is obsolete whenever we are using with loop conditional checks, because if no values are passed still it sends list with empty string, which makes it eligible to go inside the loop it should be either if data.getlist("segment_id", None)!=[''] or data.get("segment_id", None)

if data.get("segment_id", None) or data.get("promo_id", None): # why is this involving segment_id even if it is not using segment_id in below piece of code


use channel_code or promo_id (in requests object) to query promochannel table to get promo_id and promo_name

are we using segment_config_id, maximize anywhere in the (list API response) front end
after segment_config_id replaced by segment_id use that segment_id to fetch segment_name






































observations:
no default values in swagger for 
	promo-
		offer_configuration/dsmodel
		offer_configuration/edit -> giving results for offer_config_id->1
		offer_configuration/export/scenario_offers/1
		offer_configuration/save/2 -> giving 400->data": "offer_duration is required for POST,PUT
		offer_configuration/scenario_offers/1001 ->1001

offer_configuration/scenario_metrics->post-500 ->"data": "Data is not available"
offer_configuration/export/scenario_metrics->http code-500 ->"data": "Data is not available"
offer_configuration/getitem/ -http -500
offer_configuration/item/ -> giving 200 (because of JsonResponse) for error
offer_configuration/objective/ -> giving 200 for error (same as above)
offer_configuration/product-category/-> giving 200 for error (same as above)
offer_configuration/promochannel/-> giving 200 for error (same as above)
offer_configuration/promomechanic-> giving 200 for error (same as above)
offer_configuration/promoobjective
offer_configuration/segment/-> giving 200 for error (same as above)



offer_configuration/promoobjective/list-> JsonResponse->500 -> TypeError: 'int' object is not callable
offer_configuration/segment/list-> (same as above)
offer_configuration/scenario_metrics/report ->data": "Data is not available",->500
done->api/resetpasswordtoken/ ->message": "module 'datetime' has no attribute 'now'"->500
how line-> reset_password_token_created.send(sender=self.__class__,reset_password_token=token,) is getting linked to line request_info=tmpObj, created_ts=datetime.datetime.now() in send_email.py?






imported timedelta (from datetime import timedelta) in /home/saivinil_pratap/github-repos/ViT/vitapi_promo/apps/scenario_planner/service.py, changed prev_one_month = datetime.now() - datetime.timedelta(30) to prev_one_month = datetime.now() - timedelta(30) in get_offers method of ScenarioOfferList class
changed request_info=tmpObj, created_ts=datetime.now() to request_info=tmpObj, created_ts=datetime.datetime.now() in SendEmail method of /home/saivinil_pratap/github-repos/ViT/vitapi_promo/apps/utils/send_email.py

remove breakpoints